### ISSUE TITLE
Calculate stats for each unit

### ISSUE THREAD

**Issue by JesseCrocker** [OpenBounds/OpenHuntingData#411]
- [x] #407 Calculate % public land for each unit
- [x] #408 Calculate % of land cover types for each unit
- [x] #409 Calculate average monthly precip and temperature for each unit
- [x] #410 Calculate min/max elevation for each unit

**Comment by JesseCrocker** [comment]
This library seems like it will handle calculating stats from rasters: https://github.com/perrygeo/python-rasterstats
